# Generated by Django 4.1 on 2022-09-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='whatsapp',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=50)),
                ('personaldata', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='portifolio.personaldata')),
            ],
        ),
    ]
