# Generated by Django 4.1 on 2022-09-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_personaldata_whatsapp_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('aboutme', models.TextField()),
                ('personaldata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portifolio.personaldata')),
            ],
        ),
    ]
