# Generated by Django 4.1 on 2022-09-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_socialmedia_skills_alter_socialmedia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='skills',
            field=models.BooleanField(default=False),
        ),
    ]
