# Generated by Django 4.1 on 2022-09-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_alter_personaldata_whatsapp_alter_socialmedia_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtititle', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('linkgithub', models.CharField(blank=True, max_length=100)),
                ('linkdeploy', models.CharField(blank=True, max_length=100)),
                ('datainfo', models.CharField(blank=True, max_length=30)),
                ('section', models.CharField(choices=[
                 ('1', 'About'), ('2', 'Curriculum'), ('3', 'Services'), ('4', 'Portfolio')], max_length=1)),
                ('personaldata', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='portifolio.personaldata')),
            ],
        ),
    ]
