# Generated by Django 4.1 on 2022-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0008_card_cover_personaldata_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cover',
            field=models.ImageField(blank=True, upload_to='portifolio/projects/cover/%Y/%m/%d/'),
        ),
    ]
