# Generated by Django 4.1 on 2022-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0010_barprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='pdf',
            field=models.FileField(blank=True, upload_to='portifolio/user/pdf/%Y/%m/%d/'),
        ),
    ]
