# Generated by Django 4.1 on 2022-10-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0011_personaldata_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='personaldata',
        ),
    ]
