# Generated by Django 4.1 on 2022-10-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0012_remove_socialmedia_personaldata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='MiniCard',
        ),
    ]
