# Generated by Django 4.1 on 2022-10-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0014_remove_about_personaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barprogress',
            name='personaldata',
        ),
    ]
