# Generated by Django 4.1 on 2022-10-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0015_remove_barprogress_personaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='personaldata',
        ),
    ]
