# Generated by Django 4.1 on 2022-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0017_alter_card_datainfo_alter_card_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
