# Generated by Django 4.1 on 2022-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0019_alter_card_cover_alter_personaldata_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='title',
            field=models.TextField(),
        ),
    ]
