# Generated by Django 4.1 on 2022-11-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0020_remove_personaldata_pdf_alter_personaldata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barprogress',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
