# Generated by Django 4.1 on 2022-11-26 18:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0021_alter_barprogress_title_alter_card_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='cover'),
        ),
    ]
